---
- name: Install dependencies (Debian)
  become: true
  apt:
    update_cache: true
    name:
      - ca-certificates
      - curl
- name: Create keyrings directory
  become: true
  file:
    path: /etc/apt/keyrings/
    state: directory
    mode: "0775"
- name: Download GPG
  get_url:
    url: https://download.docker.com/linux/{{ ansible_facts.ansible_distribution | lower }}/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 444
- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch={{ ansible_facts.ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_facts.ansible_distribution | lower }} {{ ansible_facts.ansible_distribution_release }} stable"
    state: present
    filename: docker
- name: Install docker-ce
  become: true
  apt:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
