# This contains all packages that need to be installed on the system
initCommands:
  unix: |
    # Install Homebrew
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    ZSH_BIN=$(command -v zsh)
    if [ $? -ne 0 ]; then
      brew install zsh
      ZSH_BIN=$(brew --prefix)/bin/zsh
      echo "$ZSH_BIN" >> /etc/shells
    fi

    chpass -s "$ZSH_BIN"
  windows: |
    # Install some linux distro
    wsl --install
    wsl rm -rf ~/*
    wsl git clone git@github.com:Marfien/dotfiles.git ~
    wsl /bin/bash ~/.bin/install.sh
packages:
  brew:
    - wget
    - curl
    - grep
    - yq
    - neovim
    - tree-sitter
    - openssl
    - python
    - openjdk@21
    - openjdk@17
    - openjdk@8
    - tofuenv
    - flux
    - helm
    - kubernetes-cli
    - derailed/k9s/k9s

casks:
  - brew: hyper
    choco: hyper
  - brew: alt-tab
  - brew: font-meslo-lg-nerd-font
    choco: nerd-fonts-meslo
  - brew: raycast

