---
- name: Install requirements (Debian)
  become: true
  when: ansible_os_family == "Debian"
  apt:
    update_cache: true
    name:
      - build-essential
      - procps
      - file
      - git
      - curl
- name: Install requirements (RedHat)
  become: true
  when: ansible_os_family == "RedHat"
  dnf:
    name:
      - "@development-tools"
      - procps-ng
      - file
      - git
      - curl
- name: Install requirements (ArchLinux)
  become: true
  when: ansible_os_family == "Archlinux"
  pacman:
    name:
      - base-devel
      - procps-ng
      - file
      - git
      - curl
- name: Install XCode Dev Tools
  shell: xcode-select --install
  ignore_errors: true
  when: ansible_os_family == "Darwin"

- name: Install brew
  become: false
  when: 0 > 1
  become_user: "{{ ansible_user_id }}"
  block:
    - tempfile: {}
      register: tempfile
    - name: Download Install Script
      get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        dest: "{{ tempfile.path }}"
        mode: "0775"
    - name: Run Install
      shell:
        cmd: "{{ tempfile.path }}"
        executable: /bin/bash
    - name: Cleanup
      file:
        path: "{{ tempfile.path }}"
        state: absent
