---
- name: Install Brew Bundle
  shell: "brew bundle --file {{ dotfiles_home }}/Brewfile"
  become: false
  become_user: "{{ ansible_user_id }}"
  environment:
    PATH: "/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:{{ lookup('env', 'PATH') }}"
