---
- name: Install requirements (Debian)
  become: true
  when: ansible_os_family == "Debian"
  apt:
    update_cache: true
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
- name: Install requirements (RedHat)
  become: true
  when: ansible_os_family == "RedHat"
  dnf:
    name:
      - "@Development Tools"
      - procps-ng
      - curl
      - file
      - git
- name: Install requirements (ArchLinux)
  become: true
  when: ansible_os_family == "Archlinux"
  pacman:
    name:
      - base-devel
      - procps-ng
      - curl
      - file
      - git
- name: Install XCode Dev Tools
  shell: xcode-select --install
  ignore_errors: true
  when: ansible_os_family == "Darwin"

- name: Install brew
  shell: "curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | /bin/bash"
  become: false
  become_user: "{{ ansible_user_id }}"
  args:
    executable: /bin/bash
    stdin: "\n"
