---
- name: Install brew
  shell: "curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | /bin/bash"
  become: false
  become_user: "{{ ansible_user_id }}"
  args:
    executable: /bin/bash
    stdin: "\n"
# - name: Install zsh
#   community.general.homebrew:
#     name: zsh
- name: Find zsh path
  shell: command -v zsh
  register: zsh_path
- name: Set zsh as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"
