- name: Setup Linux Workstation
  hosts: local
  vars:
    brew_path: /home/linuxbrew/.linuxbrew/bin
  var_files:
    - vars/packages.yml
  roles:
    - requirements-linux
    - system
    - packages
