- name: Setup dev machine
  hosts: localhost

  var_files:
  - packages.yml

  tasks:
    - name: Install brew
      vars:
        script: "{{ lookup('ansible.builtin.url', 'https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh' }}"
      shell: {{ script }}
      args:
        executable: /bin/bash
    - name: Setup ZSH
      include_tasks: tasks/setup_zsh.yml
    - name: Install packages
      loop: "{{ formulae }}"
      community.general.homebrew:
        name: "{{ item }}"
        state: present
    - name: Setup Mac
      include_tasks: tasks/setup_mac.yml
      when: ansible_system == "Darwin"

