---
- name: Create Docker Group
  become: true
  group:
    name: docker
- name: Add User to Docker Group
  become: true
  user:
    name: '{{ ansible_facts.ansible_env["USER"] }}'
    groups: docker
    append: true
