---
- name: Install dnf config-manager
  dnf:
    name: dnf-plugins-core
- name: Add docker repo
  shell: dnf config-manager --add-repo https://download.docker.com/linux/{{ ansible_facts.ansible_distribution | lower }}/docker-ce.repo
- name: Install Docker Engine
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
