#!/bin/sh

if [ -n "$WSL_DISTRO_NAME" ]; then
  args=""
  for arg in "$@"; do
    if [ -f "$arg" ]; then
      arg=$(wslpath -w "$arg")
    fi
    args="$args '$arg'"
  done
  eval powershell.exe -nologo -noprofile -command "sioyek.exe $args"
else
  exec sioyek "$@"
fi
