---
- name: Enable WSL2
  win_shell: >-
    wsl.exe
    --install FedoraLinux-42
    --name Fedora
    --set-default
- name: Install requirements on WSL
  win_shell: >-
    wsl.exe
    -d Fedora
    dnf install -y git ansible
