export SPACESHIP_PROMPT_ORDER=(
  dir
  git
  char
)

SPACESHIP_RPROMPT_ORDER=(
  exit_code
)

SPACESHIP_PROMPT_ADD_NEWLINE=true

SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_SYMBOL=""

SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_COLOR_SUCCESS="white"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_SYMBOL_ROOT="#"

SPACESHIP_DIR_TRUNC_PREFIX="…/"
SPACESHIP_DIR_PREFIX=""

SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_ORDER=(git_branch)
SPACESHIP_GIT_BRANCH_COLOR=green

SPACESHIP_GIT_STATUS_SHOW=false
