format = '$fill$line_break$directory$git_branch$character'
add_newline = false
continuation_prompt = '    '

[status]
disabled = false
format = '[$status]($style)'

[fill]
symbol = " "
style = 'white underline'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'green'

[character]
success_symbol = '[❯](bright-black)'
error_symbol = '[❯](bright-red)'
