right_format = '$cmd_duration$status'
format = '$directory$git_branch $character'
continuation_prompt = '> '

[status]
disabled = false
format = '[$status]($style)'

[fill]
symbol = "-"
style = 'black strikethrough'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
style = 'green'

[character]
success_symbol = '[❯](bright-black)'
error_symbol = '[❯](bright-red)'
